name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore workload
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish ./AlcoholTracker/AlcoholTracker.csproj -c Release -o "$env:GITHUB_WORKSPACE/release/" --nologo
      env:
        Configuration: Release
        GITHUB_WORKSPACE: ${{ github.workspace }}
    - name: Change base-tag in index.html from / to AlcoholTracker
      run: Get-Content $env:GITHUB_WORKSPACE\release\wwwroot\index.html | %{$_ -Replace "<base href=""/"" />", "<base href=""/AlcoholTracker/"" />"} |  Out-File -FilePath $env:GITHUB_WORKSPACE\release\wwwroot\index.html
      shell: powershell
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{ github.workspace }}/release/wwwroot